spring:
  application:
    name: RabbitMQ-Consumer
  rabbitmq:
    host:${SPRING_RABBITMQ_HOST:localhost}
    port:${SPRING_RABBITMQ_PORT:5672}
    username:guest
    password:guest
  ssl:
    enabled: true
    algorithm: TLSv1.2
  amqp:
    deserialization:
      trust:
        all: "true"

server:
  port: ${PORT:8085}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
