spring:
  application:
    name: SpringKafkaConsumer
  rabbitmq:
    host:${SPRING_RABBITMQ_HOST:localhost}
    port:${SPRING_RABBITMQ_PORT:5672}
    username:guest
    password:guest

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:39092}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: gid1


server:
  port: ${PORT:8081}


#tutorial:
#  client:
#    duration: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}